name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
     - name: Testing workflow
       run: echo "worflow work!"

     - name: Maven Test
       run: mvn test

     - name: Checkstyle
       run: mvn checkstyle:checkstyle
    #setup java 11 to be default
     - name: Set Java 11
       uses: actions/setup-java@v3
       with:
        distribution: 'temurin'
        java-version: '11'
